platform: linux

image_resource:
  type: docker-image
  source:
    repository: cirit/jmeter:master

inputs:
  - name: service-repo

outputs:
  - name: build-output

run:
  path: sh
  args: ["service-repo/build.sh"]